name = "discord-verification-bot"
main = "index.js"
compatibility_date = "2026-09-06"
keep_vars = true

# Configure these non-secret variables in Cloudflare Workers > Settings > Variables.
# Configure secrets separately in Cloudflare Workers > Settings > Variables and Secrets.
